# Generated by Django 4.2.7 on 2025-01-26 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieScrapeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_movies', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('directors', models.JSONField(default=list)),
                ('cast', models.JSONField(default=list)),
                ('plot_summary', models.TextField(blank=True, null=True)),
                ('scrape_sessions', models.ManyToManyField(related_name='movies', to='movies.moviescrapesession')),
            ],
            options={
                'unique_together': {('title', 'release_year')},
            },
        ),
    ]
