# Generated by Django 4.2.7 on 2025-01-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
