# Generated by Django 4.2.7 on 2025-01-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
