# Generated by Django 4.2.7 on 2025-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
